security:
    firewalls:
        main:
            stateless: true
            provider: users
            jwt: ~
            custom_authenticators:
                - App\Security\GoogleAuthenticator

    access_control:
        - { path: ^/auth/google, roles: PUBLIC_ACCESS }
        - { path: ^/delete-account, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/me, roles: IS_AUTHENTICATED_FULLY }

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email